name: Deploy APK to Firebase App Distribution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: firebase-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore file
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > signed_app.jks

      - name: Create signing.properties file
        run: |
          echo "storeFile=signed_app.jks" > $GITHUB_WORKSPACE/signing.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_WORKSPACE/signing.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_WORKSPACE/signing.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_WORKSPACE/signing.properties

      - name: Debug signing.properties
        run: cat $GITHUB_WORKSPACE/signing.properties

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build signed release APK
        run: ./gradlew assembleRelease -PsigningProperties=$GITHUB_WORKSPACE/signing.properties

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
